#+hugo_base_dir: ../
#+hugo_section: productivity
* Productivity
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_WEIGHT: 10
:END:

I do have notes recommending productivity workflows and systems that I have personally experienced using. Right now, there's mainly the Zettelkasten system that I'm using with Emacs Org-Roam.

#+hugo_paired_shortcodes: button

#+attr_shortcode: :href /productivity/zettelkasten
#+begin_button
Zettelkasten
#+end_button
* Zettelkasten
:PROPERTIES:
:EXPORT_FILE_NAME: zettelkasten
:EXPORT_HUGO_WEIGHT: 10
:END:
** Zettelkasten
This is a standardized way of note-taking where information come from readings and fleeting ideas, which are then organized and developed in permanence, building a critical mass. When put into work, the ideas are further distilled into projects which are writings meant to be published and scrutinized. This is more flexible than elementary systems of (1) taking everything into permanence, (2) the lack of a system thereof where ideas are unprocessed, and (3) notes inefficiently distributed into projects that are archived and disjointed from the knowledge frame at a whole. It is more efficient than that of an infinite canvas of mind-maps because it can be indexed and more is easily converted into writing; mind-maps in this format is still a powerful format of fleeting notes that should be deleted when processed.
#+BEGIN_QUOTE
[!WARNING]
*Mind-maps*

This is another tool that I was using heavily, but it was not discussed as counter-argument in any source covering Zettelkasten.
#+END_QUOTE
*** Official Terms For the Notes
:PROPERTIES:
:ID:       89166c8f-5add-4acf-88a8-c7b2986809d3
:END:
1. Fleeting Notes - Ideas thought of on the fly, written very roughly and will be discarded quickly once processed into permanent notes
2. Literature Notes - A type of permanent notes that allows fleeting entries but also essential entries that can be referenced back that depends on the fleeting entries of the literature notes.
3. Concept Notes - A type of permanent note which is context-independent which can provide a reference back to the literature notes used. These are the more distilled forms of the fleeting and literature notes.
4. Project Notes - Distillation from concept notes with reference from literature into works for publication.
*** Adapting "Note-taking Edge-Cases" With Heuristics
A flexible note-taking system like Zettelkasten makes things more efficient. Refusal of standardization-based efficiency comes largely from circumstances that can be simply alleviated by heuristics. These refusals are prevalent due to prior practice of the three elementary note-taking systems discussed.
**** Problem-Based (Mathematics)
When it comes to using Zettelkasten to approach mathematics, this note-taking system might be seen as an extra burden when it comes to drilling problems for a test. This contention is trivial. We can regard problem-drilling as a type of fleeting note. We analyze the pattern into a problem cookbook while drafting the permanent note. This should also help to rationalize problems you have not seen before because the patterns and connections between ideas are the focal point of study over memorization of the problems.
**** Project-Based (Programming)
We do not assume that the lack of notes in programming projects destroys its credibility, though any reliable technology of scale comes with a manual and from that users benefit from using that technology. From the perspective of a developer of a module, this gets more nuanced. You are the (one of) the creator(s) of the documentation which covers a form of argumentative writing for the most essential details. Besides the discussed notes fleeting, literature, and concept notes there is also another note called the [[id:89166c8f-5add-4acf-88a8-c7b2986809d3][project note]] which is very implementable in your average software documentation despite the traditional Zettelkasten definition for project-notes comes initially estranged\mdash{}(varying) form of drafts, bibliography, etc. are necessary components of any documentation that respects its users.
** Reference
- /How to take Smart Notes/ by Sönke Ahrens.
  - Goodreads Link: https://www.goodreads.com/en/book/show/34507927-how-to-take-smart-notes
  - My specific edition: https://library.vhmp.dev/book/13
