#+hugo_base_dir: ../
#+hugo_section: programming/teaching/roblox-lua
* Luau
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:END:
** Luau (Roblox Luau)
Roblox games uses a fork (customized version) of Lua 5.1. While students can reference the official Lua documentation, some concepts commonly used in Roblox do not exist in the official releases of Lua

As usual, the index page includes the common Roblox features associated with Roblox Scripting. The latter parts nested inside describes some of the projects students have taken part of and is used to document all types of projects.

This page records the basic setup when it comes to begin coding on Roblox. My writings on @@hugo:[programming fundamentals]({{< relref "/programming/teaching/programming-fundamentals" >}})@@ should be referenced. I include examples in Lua whenever possible.

One of the things you need to do as you get better at Roblox is the ability to be able to look up things from the [[https://create.roblox.com/docs][official reference page]] on your own.
*** Types of Scripts
There are three types of scripts in Roblox as of right: scripts, local scripts, and module scripts. The normal scripts are not actually "normal", they are code a developer writes to affect changes to the *server*. The local scripts include code that affects only a single player, other players other than the player that owns the local script do not see the changes to the game world.

#+BEGIN_QUOTE
[!TIP]
*Server vs. Client* - First-Person Shooter Example

The normal Script contains code written for the server while the Local Script contains code written for a single player.

In many games (not just in Roblox), the usage of fake-arms are employed. After all, if the player's arms are controlled by the Server in first-person, the arms movement will feature massive delay. Fake arms, or "viewmodels" are created in a Local Script that constantly sets the coordinate frame (CFrame) to that of the camera's CFrame offset by some amount.
#+END_QUOTE
**** Where to Use Each Type of Script
Both the =script= and the =local script= can be put into an object placed inside the =workspace=. This is how models work in Roblox.

For general game mechanics that transcend any model, the Roblox developer is utilize other places.
***** Script
The normal =script= otherwise called the server script should be usually placed inside =ServerScriptService=. If the script is not meant to be running, it can be placed inside =ServerStorage=.

#+BEGIN_QUOTE
[!NOTE]
*ServerStorage* - Additional Usage

The server storage can store other assets like models, sounds... or anything that's handled by the server exclusively first. The player cannot access any of the asset inside =ServerStorage=.
#+END_QUOTE
***** Local Script
=Local script= can be placed inside a =GuiObject= inside =StarterGui= as code handling each player's graphical interface. =StarterPlayerScripts= is the most common place to put a =local script= which is created and runs every time a player joins the game. =StarterCharacterScripts= is also a valid option if the player wishes for a local script to run every time the player character reloads.
*** Events - Something You See Often
Roblox uses the programming pattern called the =Observer Pattern= where a process =listens= and =notifies= state changes. The result is that whenever an specific =event= happens, like when something touches a =BasePart=, then a function that the Roblox Developer writes for that event will be called.

#+BEGIN_QUOTE
[!NOTE]
*State Changes*

In a computer program =states= are values that the computer look at constantly to decide what to do. Think of a light switch. If the light switch is off, then the room's ambiance should be dark.
#+END_QUOTE

#+BEGIN_QUOTE
[!WARNING]
*Know Prerequisites*

If you have difficulty understanding the writing so far, make sure you know what a =function= and a =loop= is first.
#+END_QUOTE
**** How are Listeners Implemented
This is not something that you have to worry about. However, you might understand events more if you visualize that =listeners= are a separate thing that waits for a certain condition to occur. Here's pseudo-code of what a =listener= might be.

#+BEGIN_SRC
  while game is running:
    if event_condition:
      for every function we are given:
         function(necessary arguments for this event)
#+END_SRC
**** How to Use the Listeners
All we need to do is to give the listener the functions we would like to be called when the event condition occurs. Roblox also describes this in its [[https://create.roblox.com/docs/scripting/events][official documentation page on events]]. We're showcasing the =Touched= event which is listed in this [[https://create.roblox.com/docs/reference/engine/classes/BasePart#Touched][official reference page]], which I recommend reading as it's a skill you're going to have develop called =documentation referencing=.

#+attr_html: :filename ServerScriptService/Script
#+BEGIN_SRC lua
  -- Creating a part in workspace and positioning it
  -- at (x, y, z) = (0, 10 0)
  part = Instance.new("Part")
  part.Name = "Touchable"
  part.Parent = workspace
  part.Position = Vector3.new(0, 10, 0)

  -- The function we're giving to the Touched
  -- Event as argument
  function onTouch(basePartTouched)
     print(basePartTouched:GetFullName())
  end

  -- Passing the our function to the Connect function
  -- The Connect function is inside every event in Roblox
  part.Touched:Connect(onTouch)
#+END_SRC

Notice that =Touched= is an event that exists inside the part. =Touched= itself is also a table. We then use the =Connect= function that is inside the =Touched= event. Every =event= needs an argument which is the =function= that should be called when the event occurs. Every =event= can handle and keep track of multiple =functions=. You can assign many =functions= to a single =event=.

#+BEGIN_QUOTE
[!TIP]
*What a object in Roblox Is*

Every single game object in Roblox you see is actually a table that has been modified with a =metatable=. This game object table is modified so that it can access its =children= which are other game objects it stores. It can also access its properties and other non-properties.

All of this is possible through the =.= operator to access something inside another thing.
#+END_QUOTE

A common coding pattern in Roblox code is the usage of lambdas (alias =in-line functions=). Lambdas are anonymous functions (functions without a name). Here's the same code that uses a =lambda= instead of a =named function=.

#+attr_html: :filename ServerScriptService/Script
#+BEGIN_SRC lua
  -- Creating a part in workspace and positioning it
  -- at (x, y, z) = (0, 10 0)
  part = Instance.new("Part")
  part.Name = "Touchable"
  part.Parent = workspace
  part.Position = Vector3.new(0, 10, 0)

  -- Passing a lambda to the Connect function
  -- The Connect function is inside every event in Roblox
  part.Touched:Connect(function(basePartTouched)
        print(basePartTouched:GetFullName())
  end)  
#+END_SRC
* Obby (WIP)
:PROPERTIES:
:EXPORT_FILE_NAME: obby
:END:
** Obby
An obby is a classic obstacle game in Roblox. This project focuses on coding certain common components of an Obby from scratch.
*** List of Common Mechanics
Some common mechanics include
1. Damage Brick - Kill Brick, Fire Brick
2. Path Pattern - A correct path is illuminated before disappearing for a couple of seconds
3. Stages System - Spawn locations
4. Progress Saving - Saving The stage the player is on through DataStore.
*** Damage Brick
When the player touches a damage brick, their health will decrease. We're going to be using the =Touched= event for both this and two different bricks.
**** Prerequisites
Knowledge of =functions= is required as well as =conditionals=.
**** Kill Brick
Kill Brick simply sets the health of the player to zero when the player touches it.
***** Instructions
#+hugo_paired_shortcodes: %steps
#+begin_steps
1. Create a =script= inside the kill brick.
2. Create a variable for your kill brick.
3. Create an empty named function
4. Call the =Connect= function of the =Touched= event inside the kill brick
5. Implement the empty named function
#+end_steps
****** Implementing the empty named function
Here are the specific sub-steps of step 5.

#+begin_steps
1. Make sure the part touching our kill brick is a body part.
2. Set the =Health= property of the character model's =Humanoid=.
#+end_steps
***** Implementation Hints, Solutions
****** Step 1 - Activity Setup
Simply create a Part in =workspace= and insert a =script= inside the Part.
#+BEGIN_QUOTE
[!TIP]
*Script or Local Script*

In Roblox, we only use a =local script= for graphical interface elements, things the player should only see or experience, and the events of the character's humanoid.
#+END_QUOTE
****** Step 2 - Making Variable For Kill Brick
We're creating a =variable= so think of a name. e.g. =killbrick=, =part=.

Remember how variable initialization/assignment work in Lua. On the right side of ===, how can you access the kill brick? Remember that the script we're writing in is inside the kill brick.

#+hugo_paired_shortcodes: %details
#+attr_shortcode: :title Solution
#+begin_details
#+attr_html: :filename workspace/KillBrick/Script
#+BEGIN_SRC lua
  killBrick = script.Parent
#+END_SRC
#+end_details
****** Step 3 - Making an Empty Function
Choose a name for your =function=. Look at the [[https://create.roblox.com/docs/en-us/reference/engine/classes/BasePart#Touched][documentation reference page]] for the =Touched= event, what parameter(s) do we need?

#+attr_shortcode: :title Solution
#+begin_details
#+attr_html: :filename workspace/KillBrick/Script
#+BEGIN_SRC lua
  function processKill(otherPart: BasePart)
  end
#+END_SRC
#+end_details
****** Step 4 - Passing Empty Function to Connect Function
Access the =Touched= event inside the =KillBrick=, then call the =Connect= function and pass in our empty function in as argument.

#+attr_shortcode: :title Solution
#+begin_details
#+attr_html: :filename workspace/KillBrick/Script
#+BEGIN_SRC lua
  killBrick = script.Parent -- From Step 2

  -- Step 3
  function processKill(otherPart: BasePart)
  end

  killBrick.Touched:Connect(processKill)
#+END_SRC
#+end_details
****** Step 5 - Implementing the Empty Function
First, we have to make sure that the argument we received is an actual body part because the =Touched= event [[https://create.roblox.com/docs/en-us/reference/engine/classes/BasePart#Touched][occurs for any base part]] that moved to touch. In order to do this, we check if there's a =Humanoid= inside the =Parent= of the body part. If there isn't, then =return= from the function early.

#+BEGIN_QUOTE
[!TIP]
*Parent of Body Part*

The parent of every body part is the character model.
#+END_QUOTE

#+BEGIN_QUOTE
[!TIP]
*Use FindFirstChild*

Use the function =FindFirstChild= in order to safely access a =child= (nested object) of another object. =FindFirstChild= requires a =string= as argument which is the name of the child that should be attempted to access. =FindFirstChild= returns =nil= if it could not find the child of given name or it gives the actual =child= back.

Check out the [[https://create.roblox.com/docs/en-us/reference/engine/classes/Instance#FindFirstChild][reference documentation page on =FindFirstChild=]].
#+END_QUOTE

#+attr_shortcode: :title Solution - Making Sure It's a Body Part
#+begin_details
#+attr_html: :filename workspace/KillBrick/Script
#+BEGIN_SRC lua
  function processKill(otherPart: BasePart)
     local potentialCharacter = otherPart.Parent
     local potentialHumanoid = potentialCharacter:FindFirstChild("Humanoid")
     if not potentialHumanoid then return end
     -- Equivalent: if potentialHumanoid == nil then return end
  end
#+END_SRC
#+end_details

Then, we simply set the =Health= property of the character's =humanoid= to 0.

#+attr_shortcode: :title Solution - Setting Property Health
#+begin_details
#+attr_html: :filename workspace/KillBrick/Script
#+BEGIN_SRC lua
  function processKill(otherPart: BasePart)
     local potentialCharacter = otherPart.Parent
     local potentialHumanoid = potentialCharacter:FindFirstChild("Humanoid")
     if not potentialHumanoid then return end
     -- Equivalent: if potentialHumanoid == nil then return end

     potentialHumanoid.Health = 0
  end  
#+END_SRC
#+end_details
***** Complete Solution
Before you look at the complete solution, make sure to struggle first.

#+hugo_paired_shortcodes: %details
#+attr_shortcode: Solution
#+begin_details
#+attr_html: :filename workspace/KillBrick/Script
#+BEGIN_SRC lua
  part = script.Parent

  function burn(otherPart)
      -- First, we confirm if the otherPart is a body part
      local character = otherPart.Parent
      local humanoid = character:FindFirstChild("Humanoid")
      if not humanoid then return end

      humanoid.Health = 0
  end

  part.Touched:Connect(burn)
#+END_SRC
#+end_details
**** Fire Brick
Unlike the Kill Brick, the fire brick deals damages over time and is much more complex. We have to make cool-down system.

Burn Brick #1
Simply decrease the health instead of setting it to 0.

#+attr_shortcode: :title Solution
#+begin_details
#+BEGIN_SRC lua
  part = script.Parent

  function burn(otherPart)
      -- First, we confirm if the otherPart is a body part
      local character = otherPart.Parent
      local humanoid = character:FindFirstChild("Humanoid")
      if not humanoid then return end

      humanoid.Health -= 5
      -- Code above is same as:
      -- humanoid.Health = humanoid.Health - 5
  end

  part.Touched:Connect(burn)  
#+END_SRC
#+end_details

Burn Brick #2 - Countdown system attempted

#+attr_shortcode: :title Solution
#+begin_details
#+BEGIN_SRC lua
  -- the function os.time() returns seconds since January 1st of 1970.
  savedTime = os.time()

  function burn(otherPart)
      -- First we once again confirm if otherPart is a body part
      local character = otherPart.Parent
      local humanoid = character:FindFirstChild("Humanoid")
      if not humanoid then return end

      -- Cooldown of 1 second
      if os.time() - savedTime > 1 then
          humanoid.Health -= 5
      end
  end
#+END_SRC
#+end_details

Bug: In the first version, we thought the burning effect worked because multiple body parts was causing the burn.
In the next version we have to begin integrating the event TouchEnded to deal damage gradually until the player stops touching the part

#+attr_shortcode: :title Solution
#+begin_details
#+BEGIN_SRC lua
  charactersTouching = {
      -- ["Player1"] = {12312512, true, <Character>}, -- touching is still occuring.
      -- ["Player2"] = {123451243, false, <Character>}, -- touch stops about to be removed from the table
      -- ["Player3"] = nil -- not actually in the table anymore
  }

  part = script.Parent

  function isCharacter(otherPart: BasePart)
      local potentialCharacter = otherPart.Parent
      local humanoid = potentialCharacter:FindFirstChild("Humanoid")
      if humanoid then return potentialCharacter end
      return false
  end

  function startBurn(otherPart: BasePart)
      local character = isCharacter(otherPart)
      if not character then return end
      if charactersTouching[otherPart] then return end
      charactersTouching[otherPart] = {os.time(), true, character}
  end

  function stopBurn(otherPart: BasePart)
      local character = isCharacter(otherPart)
      if not character then return end
      charactersTouching[character.Name][2] = false
  end

  function burnOnStandBy()
      for characterName, data in charactersTouching do
          if not data[2] or not data[3] then
              charactersTouching[characterName] = nil
              continue
          end
          if os.time() - data[1] > 1 then
              data[3].Humanoid.Health -= 5
          end
      end
  end

  part.Touched:Connect(startBurn)
  part.Touched:Connect(stopBurn)
  part.Heartbeat:Connect(burnOnStandby)
#+END_SRC
#+end_details
